import type { Metadata } from 'next';
import { Montserrat, Open_Sans } from 'next/font/google';
import './globals.css';
import Header from './components/Header';

const openSans = Open_Sans({
	variable: '--font-open-sans',
	subsets: ['latin'],
});

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Red-Post',
	description:
		'Custom world building app created to learn nextjs. Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${openSans.variable} ${montserrat.variable} antialiased`}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
