import type { Metadata } from 'next';
import { Montserrat, Open_Sans } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Footer from './components/Footer';

import { ThemeProvider } from 'next-themes';

const openSans = Open_Sans({
	variable: '--font-open-sans',
	subsets: ['latin'],
});

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Red-Post',
	description:
		'Custom world building app created to learn nextjs. Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const styles = {
		body: 'fixed h-[100vh] w-[100vw] flex flex-col',
		contentWrapper:
			'min-h-[calc(100vh-100px)] w-full bg-linear-65 from-purple-400 to-pink-300 dark:from-purple-900 dark:to-pink-900 overflow-y-auto p-2',
	};

	return (
		<html suppressHydrationWarning lang='en'>
			<body
				className={`${openSans.variable} ${montserrat.variable} ${styles.body} antialiased`}
			>
				<ThemeProvider attribute='class'>
					<Header />
					<div className={styles.contentWrapper}>{children}</div>
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	);
}
